### ISSUE TITLE
주제

### ISSUE THREAD

**Issue by oddheo** [spckce/document#1]
정하기

**Comment by spckce** [comment]
어플로 원격으로 PC 제어

**Comment by pso1027** [comment]
p2p 통화

**Comment by pshsh88** [comment]
WebRTC를 이용한 앱 (팀보이스)

**Comment by oddheo** [comment]
인디게임

**Comment by pshsh88** [comment]
React Native App (http://facebook.github.io/react-native/)

**Comment by oddheo** [comment]
딥러닝

**Comment by jooojub** [comment]
Up-cycling Using Smart Phone

**Comment by jooojub** [comment]
SPC 메신저
- 기능 plugin 형식으로 확장 가능 (채팅, 보이스, 파일 전송 등등)
- 웹, 앱, 리눅스, 윈도우 모두 가능

**Comment by pshsh88** [comment]
크롬 익스텐션 플러그인 개발

**Comment by jooojub** [comment]
마켓에 올려 donation 받을 수 있는 것들?

**Comment by jooojub** [comment]
@pshsh88 특정 단어를 모자이크 처리하여 웹사이트에서 스포 안당하게 하기

**Comment by pshsh88** [comment]
@jooojub 
좋네 ㅋㅋㅋ 필터링 단어 등록해두면 관련 컨텐츠는 노출 안하는걸로

**Comment by pso1027** [comment]
머신러닝 - 만능비서챗봇

**Comment by pshsh88** [comment]
블록체인 기반 시스템 구현 (맛보기)
 (ex) 탈중앙화 투표 시스템

**Comment by jooojub** [comment]
몸풀기: grep in windows (폴더, 파일 선택 후 mouse context menu에서 grep 선택 후 결과 출력)

**Comment by oddheo** [comment]
그래서
여튼뭔가 쉬운걸로 첫삽을 떴으면좋겠는데...

**Comment by jooojub** [comment]
@oddheo ㅇㅇ 조금은 익숙한 걸로 한달 정도 기간으로 가능한걸로

**Comment by jooojub** [comment]
서버나 데스크탑에 있는 파일을 url로 공유할 수 있는 서버프로그램 (with password) 

- use case
 : 서버에 공유를 원하는 파일 선택
 : 생성된 URL을 다운로드 윈하는 사용자에게 공유
 : 사용자가 URL로 접근하면 웹 페이지 접근하여 password 입력
 : 다운로드 시작

**Comment by oddheo** [comment]
보이스챗으로 결정
